### ISSUE TITLE
westeurope is missing in allowed locations

### ISSUE THREAD

**Issue by TimArrow** [microsoft/azurechat#158]
Hi there, thanks for the updated version. I figured that westeurope is not an option for the "Open AI Location" when deploying the infrastructure.

**Comment by baptistepa** [comment]
Use the  francecentral option, this one is closest to westeurope.

**Comment by TimArrow** [comment]
Thats a nice Workaround but not the solution i´d say :)

**Comment by baptistepa** [comment]
Well it is the solution since the models that are being used are not deployed in westeurope yet. You can find the regions and models in the docs [here](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#model-summary-table-and-region-availability).

**Comment by derkoe** [comment]
It works when you also change the `chatGptModelVersion` to `0301`
