### ISSUE TITLE
Upload : request failed with status 404

### ISSUE THREAD

**Issue by methodidacte** [microsoft/azurechat#160]
Trying to upload a small PDF file, I get a 404 issue.

I see a new index in Azure Search, named "azure-chat" but empty.

**Comment by thivy** [comment]
> Trying to upload a small PDF file, I get a 404 issue.
> 
> I see a new index in Azure Search, named "azure-chat" but empty.

Coud you please check if changing the Azure document intelligence endpoint work?

Change from:
# capitalise this Azure AI Document Intelligence
AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT="https://YOURLOCALTION.api.cognitive.microsoft.com/"

Change to:
# capitalise this Azure AI Document Intelligence
AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT="https://Name_of_Document_Intelligence.api.cognitive.microsoft.com/"
