### ISSUE TITLE
GPT-4

### ISSUE THREAD

**Issue by grayjeremy** [microsoft/azurechat#169]
Can this support GPT-4?  I seem to remember a button on the previous where you could pick the model.  Is it as easy as changing the model name [here](https://github.com/microsoft/azurechat/blob/main/infra/main.bicep#L26 )?

**Comment by E-Rock-001** [comment]
The old version had a selector, but it didn't do anything. I had a working version on the old project that made it selectable, and it worked, so you could put that back. To switch the whole thing, you need to add a deployment in azure to use the gpt4 model, then update the AZURE_OPENAI_API_DEPLOYMENT_NAME in env.local.

**Comment by grayjeremy** [comment]
I am happy with this as a work-around, should we keep the issue around in case someone wants to put the model-picker button back in?

**Comment by riosengineer** [comment]
For those also wondering, if you amend the Azure Web App config value AZURE_OPENAI_API_DEPLOYMENT_NAME to match your GPT model then it will work in Azure too. However, you need to amend the ARM template on deployment to allow eastus2 region (or any current GPT4 region as east us is not supported yet).

**Comment by grayjeremy** [comment]
> ion on the old project that made it selectable, and it worked, so you could put that back. To switch the whole thing, you need to add a deployment in azure to use the gpt4 model, then update the AZURE_OPENAI_API_DEPLOYMENT_NAME in env.local.

I'm looking for this code and can't find it.  Can you point me in the right direction?  My MSFT alias is jegra if its private.

**Comment by asimmon** [comment]
@grayjeremy I've forked this Azure Chat repo and re-introduced the chat model selector for gpt-3.5-turbo and gpt-4, like the previous azurechatgpt repo (but this one works). Check this PR and you'll find the relevant changes:
https://github.com/asimmon/blugpt/pull/1
