### ISSUE TITLE
AOI Endpoint URL Creation - Doesn't work with an API-M / App Gateway or other interceptor.  

### ISSUE THREAD

**Issue by grayjeremy** [microsoft/azurechat#170]
Because of regulatory concerns, I need to put an API Manager in front of my AOI instance. Additionally, it allows me to do pre and post processing of prompts/completions and additional content management. 

I'd like to be able to send this a FQDN of the AOI instance instead of an instance name and have this not create a new instance and point at my current interface.

**Comment by kbedhu** [comment]
Following. This is an important blocker for us

**Comment by thivy** [comment]
@grayjeremy @kbedhu have you tried changing the base path? 

 https://js.langchain.com/docs/modules/model_io/models/chat/integrations/azure 


`const model = new ChatOpenAI({
  temperature: 0.9,
  azureOpenAIApiKey: "SOME_SECRET_VALUE", // In Node.js defaults to process.env.AZURE_OPENAI_API_KEY
  azureOpenAIApiVersion: "YOUR-API-VERSION", // In Node.js defaults to process.env.AZURE_OPENAI_API_VERSION
  azureOpenAIApiDeploymentName: "{DEPLOYMENT_NAME}", // In Node.js defaults to process.env.AZURE_OPENAI_API_DEPLOYMENT_NAME
  azureOpenAIBasePath:
    "https://westeurope.api.microsoft.com/openai/deployments", // In Node.js defaults to process.env.AZURE_OPENAI_BASE_PATH
});`

**Comment by jupiter19914** [comment]
I was able to add the base path config to the app service to direct through APIM. Works nice!

**Comment by jupiter19914** [comment]
> Following. This is an important blocker for us

Add the openai base path config setting and set the value to your APIM url.  
"https://<your-apim-service>.azure-api.net/openai/deployments/"

**Comment by grayjeremy** [comment]
There are likely to be several other issues (mostly around where to store the keys), I'll do a doc PR when they are all resolved.

**Comment by enrique-ochoa** [comment]
I added the AZURE_OPENAI_BASE_PATH variable but the web app is ignoring that setting and just going straight to the Open AI end point. Has anything changed since this workaround was suggested?
