### ISSUE TITLE
Allow users to add system prompts to customize their interaction with gpt 

### ISSUE THREAD

**Issue by SabareeshGC** [microsoft/azurechat#179]
letting users to save their system prompts and customize more by telling more about you and and how you want got to respond similar to how chatgpt does

**Comment by jimmylevell** [comment]
My PR addresses some of your concerns: https://github.com/microsoft/azurechat/pull/174

**Comment by SabareeshGC** [comment]
@jimmylevell  not sure this is letting users to save their system prompts and customize more by telling more about you and and how you want got to respond similar to how chatgpt does

**Comment by SabareeshGC** [comment]
@thivy  can you provide some explanation on why this was closed
