### ISSUE TITLE
Mobile View: Giving users the possibility to open and close the left menu containing the chat list

### ISSUE THREAD

**Issue by giuliohome** [microsoft/azurechat#183]
Refer to the whole [thread here](https://github.com/giuliohome/giuliohome.github.io/issues/1#issuecomment-1734990164). Related PR changes could be ported here into this repo as well.

Question: Do you find it reasonable for me to send a PR that includes both this enhancement for mobile view, allowing users to open and close the left menu containing the chat list, and the previously opened issue regarding [title edit](https://github.com/microsoft/azurechat/issues/182)? These changes overlap in the code part related to the 'chat menu' component. Sending two separate PRs might introduce dependency issues, so combining them into one could simplify the process. Your feedback on this proposal is appreciated.

**Comment by oliverlabs** [comment]
Thanks, @giuliohome :) 

@thivy, would you be OK with this functionality?

**Comment by giuliohome** [comment]
@oliverlabs they have done

**Comment by giuliohome** [comment]
@oliverlabs maybe it is enough to delete (or reduce) `min-w-[380px]` from this line

https://github.com/microsoft/azurechat/blob/main/src/components/chat/chat-row.tsx#L42

I'm under the impression that they don't want I touch the code though... I've already opened a PR and it has been ignored till now..

**Comment by oliverlabs** [comment]
@giuliohome, many thanks. This fixes the issue, indeed!
