### ISSUE TITLE
Chat History Disappears 

### ISSUE THREAD

**Issue by grayjeremy** [microsoft/azurechat#184]
The chat history works great for 2-3 days, then clears and I have to start over.  The data is available in CosmosDb, it's just not shown on the UI.

**Comment by giuliohome** [comment]
You likely must export your AZURE_COSMOSDB_URI and AZURE_COSMOSDB_KEY environment variables.

**Comment by grayjeremy** [comment]
These are set by default in the app configuration and still exist for me.  This works across page refreshes and different browsers for a couple days, then disappears.

**Comment by giuliohome** [comment]
So, you confirm that you have read and done this https://github.com/microsoft/azurechat/blob/7a078d3f5616817e2892dccab1febf32d4473a7a/docs/7-environment-variables.md?plain=1#L16 right?

To be honest, I've not used the bicep template, but I've set the env var manually in my azure portal. There are many equivalnt ways to do that, one could use terraform, for exmple.

In my case this is working without issues for a moonth, at least.

**Comment by grayjeremy** [comment]
![image](https://github.com/microsoft/azurechat/assets/37842906/37255f38-1a5b-4ea3-a518-bd67f1b0ac7d)

**Comment by giuliohome** [comment]
Excellent! @grayjeremy thanks

Another vague idea... in my private repo code, which I am really using, I don't have the [fix race condition commit](https://github.com/microsoft/azurechat/commit/00f25ee7a5816df2d272c4e11de9184cb41d1252)... I don't know whether it could be relevant

**Comment by grayjeremy** [comment]
That smells right but I'm up to date with main.

**Comment by giuliohome** [comment]
Okay, out of curiosity, I'll set up another web app from the current main branch and keep it for a few days to check if that commit really makes a difference. I want to see if I encounter the same issue with the second setup.

**Comment by giuliohome** [comment]
Wait, trivial question, are you using either the Azure or GitHub provider consistently? Have you stored the secrets for both authentication providers in the web app configuration on the Azure Portal (as shown in my screenshot)? In that case, please note that if you switch from one authentication provider to another, you won't be able to see the messages associated with the other user ID.

![image](https://github.com/microsoft/azurechat/assets/3272563/28e12a52-2fcb-4d3b-b047-005fffaf5d47)

**Comment by giuliohome** [comment]
You can verify the above by running a query like this:

```sql
SELECT count(1) as 'count', c.userId from c group by c.userId
```
This query will help you count the occurrences of each user ID in your collection.

![image](https://github.com/microsoft/azurechat/assets/3272563/d016946a-fc4f-4c77-8613-e9e0ab088a0b)

**Comment by giuliohome** [comment]
> Okay, out of curiosity, I'll set up another web app from the current main branch and keep it for a few days to check if that commit really makes a difference. I want to see if I encounter the same issue with the second setup.

Done.

Please note that I've had to add the [admin user](https://github.com/giuliohome-org/azurechat/blob/main/docs/5-add-identity.md#configure-an-admin-user)'s email to enable the reporting section.

![image](https://github.com/microsoft/azurechat/assets/3272563/fb9c41d7-5ac9-4fde-968b-7691d16f3afa)


You may want to consider running the following query to analyze the difference between regular users (chat menu) and the admin (reporting):

```sql
SELECT count(1) as 'count', c.userId, c.isDeleted from c where c.type='CHAT_THREAD' group by c.userId, c.isDeleted
```

Will keep verifying for a few days.

**Comment by grayjeremy** [comment]
My fault on this one, my scheduled deployment was re-deploying cosmos and truncating the items in this container.

**Comment by giuliohome** [comment]
Related: https://github.com/microsoft/azurechat/pull/205
