### ISSUE TITLE
Azure Deployment /api/auth/error Page

### ISSUE THREAD

**Issue by vtxjholter** [microsoft/azurechat#187]
Build is successful however when selecting either login option I get dropped to an /api/auth/error page that only shows "Error" and the name of my app service.  I have updated NEXTAUTH_URL to both my app service URL as well as the Custom URL configured for it.

My deployment and login with Microsoft 365 work fine when running locally and using NEXTAUTH_URL=https://localhost:3000

Am I missing something in the docs that needs to be changed to deploy to azure, or where do I start looking for logs?

**Comment by giuliohome** [comment]
Not only must the Build job be successful, but also the Deploy job.
You need to set the environment variables on Azure App Services, as explained [here](https://github.com/giuliohome-org/azurechat/blob/main/docs/5-add-identity.md). Additionally, please remember to change the redirect URI etc. in the configuration of the OAuth2 Provider (e.g., Github) as well

![image](https://github.com/microsoft/azurechat/assets/3272563/28e12a52-2fcb-4d3b-b047-005fffaf5d47)

![image](https://github.com/microsoft/azurechat/assets/3272563/6d524f53-c822-4481-bac4-79bbf9f6b3b1)

**Comment by vtxjholter** [comment]
I was missing the Auth Variables in the webapp.  I had gone through Identity during local deployment then skimmed it during Azure deployment and missed the callout that it was needed in the webapp variables as well.

Thank you.
