### ISSUE TITLE
[feature] Word/Office document support?

### ISSUE THREAD

**Issue by riosengineer** [microsoft/azurechat#202]
The docs only mention PDFs and nothing else: https://github.com/microsoft/azurechat/blob/main/docs/6-chat-over-file.md

However, there was a backlog item suggested for this already here https://github.com/microsoft/azurechat/issues/115 but the board item has been moved to done. The bot still gives you an error if you try to upload a word document for example - either I'm missing something in the docs or it's still outstanding?

Is it going to be possible to add wider support for word and other office document support like power point or excel with the direct file upload method?

Thanks

**Comment by davidxw** [comment]
Thanks @riosengineer - the Document Intelligence prebuilt model we were using didn't support Office docs - we have updated to "prebuilt-read" which should fix this issue.
(https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/concept-read?view=doc-intel-3.1.0#input-requirements)
