### ISSUE TITLE
Compare to other repo ?

### ISSUE THREAD

**Issue by nselvase** [microsoft/azurechat#207]
Not an issue but would like to get an opinion:

**What is the difference between this repo and [https://github.com/Azure-Samples/azure-search-openai-demo](url) ?**

**Comment by davidxw** [comment]
Hi @nselvase , these repos are similar in many respects, especially in their demonstration of the RAG approach to chatting over documents.  Azure Chat offers a few additional features however such as general chat, mandatory authentication, and an application wide persistent chat history accessible to authorised users.

**Comment by craigofnz** [comment]
@nselvase, opinions and all. But at currently functionality, they could be complementary for out of the box demonstration purposes:

- Azure Chat is better suited for self-service, adhoc use and user provided content
- azure-search-openai-demo is better suited for pre-provisioned enterprise data

**Comment by nselvase** [comment]
Thank you!
