### ISSUE TITLE
Secure Report and Chat Sharing Features.

### ISSUE THREAD

**Issue by ArunkumarRamanan** [microsoft/azurechat#209]
# Issue Description: 

The current architecture of our application allows the reporting pages to be publicly accessible to anyone with the knowledge of a specific URL format. These URLs typically follow the format `chat.azurewebsite.net/reporting/<url_unique_identifier>`. Anyone with this URL can freely access these pages without an enforced security measure or authentication process. This design creates an inherent vulnerability that poses a severe threat to our user's data privacy and security. 

For instance, potentially sensitive, confidential, or personally identifiable data is automatically at elevated risk of exposure, particularly in scenarios where unauthorized individuals can guess or obtain the unique identifiers required to navigate to these reports.

Practically speaking, this could mean a breach of user confidentiality, and could lead to potential misuse of data reported on these pages. Furthermore, such data breaches not only diminish our users' trust and loyalty but they can also lead to lawsuits and regulatory penalties depending on the nature of data being exposed. 

To mitigate this severe security concern, we propose the following actions:

1. **Access Control**: Implement a mechanism to control access to these report pages, such as user roles and permissions-based security model.

2. **Authentication and Authorization**: Adopt a mandatory sign-in process for all users attempting to access these pages. Determine user privileges based on their roles within the organization to ensure appropriate access levels. 

3. **Public URL Flag**: Make sure URLs are publicly accessible only when the `Public URL access` feature is flagged on for specific reports. By default, all URLs should be private and secure.

4. **Encryption**: Use encrypted SSL connections for transmission of sensitive data.

5. **Audit Logs**: Maintain a record of everyone who accesses a report, including what actions they carry out whilst there to build a clear audit trail. 

We kindly request that the team prioritize this issue, considering the serious legal and reputational risks involved. Please address this concern a priority, and provide updates on the progress of resolving this issue within this thread.

**Comment by thivy** [comment]
@ArunkumarRamanan All pages and APIs require authentication for access, and there is an additional 'admin' flag to limit reporting access only to administrators. 

Please check the 'middleware.ts' file for protected  endpoints

**Comment by thivy** [comment]
@ArunkumarRamanan all sub paths under /reporting are protected as part of the middleware. 

https://github.com/microsoft/azurechat/blob/main/src/middleware.ts

Are you able to reproduce this issue and share in more detail? Happy to take a look and fix if required.

**Comment by grayjeremy** [comment]
You've spent a lot of time telling how you want this feature to be secured, but not a lot describing what you'd like to do.  I don't see a clear ask for new functionality.  Change your prompt to specify the creation of functional requirements for a chat sharing feature.  Here is the [openai FAQ for chat sharing](https://help.openai.com/en/articles/7925741-chatgpt-shared-links-faq).

**Comment by grayjeremy** [comment]
OK, now modify your prompt to include your security requirements, alongside your functional requirements, point it at the files int the "\src\app" folder (making sure you don't include the favicon), and ask the LLM to write the code in typescript.  This will probably be more than 8k of context so you may need to swap to the 32k model.  Also, what about the reporting capability you mentioned that seems to be missing from the functional requirements?
