### ISSUE TITLE
How to do a OWASP Top Ten scan using SAST tool ?

### ISSUE THREAD

**Issue by nselvase** [microsoft/azurechat#210]
**Can you please recommend how can I do a SAST (Static application security testing) testing to cover OWASP Top Ten ?**

**Comment by grayjeremy** [comment]
SAST is a function of your build and release tooling.  There are [extensions in Azure DevOps](https://learn.microsoft.com/en-us/azure/defender-for-cloud/azure-devops-extension), it is also included in the [GitHub Advanced Security](https://docs.github.com/en/get-started/learning-about-github/about-github-advanced-security) package (GitHub Enterprise only). 

OWASP also has a [page on opensource tooling](https://owasp.org/www-community/Free_for_Open_Source_Application_Security_Tools) in this area.

**Comment by nselvase** [comment]
Thank you.
