### ISSUE TITLE
I heard this is free chatgpt, is that true?

### ISSUE THREAD

**Issue by BenHerbst** [microsoft/azurechat#213]

**Comment by grayjeremy** [comment]
Cloud hosting and consumption are not free; however the software is provided under an MIT license.  

The code in this repo will deploy a private website that has similar functionality to chat.openai.com but all the cloud resources are in your Azure subscription under your control.  You will be able to utilize a private version of OpenAI's GPT-3.5 and GPT-4 large language models hosted in **your** Azure subscription which comes with [enterprise data privacy and security provisions](https://learn.microsoft.com/en-us/legal/cognitive-services/openai/data-privacy).  

The [Azure Pricing Calculator](https://azure.microsoft.com/en-us/pricing/calculator/) is a great way to estimate cloud costs.
