### ISSUE TITLE
Can't see App Service variables for OAuth App configuration

### ISSUE THREAD

**Issue by Nihal-1512** [microsoft/azurechat#228]
As part of the environment set up, we have to update the following variables:

![image](https://github.com/microsoft/azurechat/assets/148758671/2ca657af-5f03-4964-a199-f1f6cd5a7176)

However I can't see these variables on my web app resource

![image](https://github.com/microsoft/azurechat/assets/148758671/5e4c45e1-bc86-4797-aaa9-0037aa7559b0)

Any help would be appreciated, thanks

**Comment by jorupp** [comment]
If you don't see an existing one to edit, you can click "new" at the top to add it.

**Comment by Nihal-1512** [comment]
Thanks @jorupp, its fixed now and the solution works
