### ISSUE TITLE
How to make changes to Front-End 

### ISSUE THREAD

**Issue by Nihal-1512** [microsoft/azurechat#233]
I successfully deployed the application using Windows PowerShell. If I wanted to make changes to the front-end of the application and redeploy the front-end only, how would I go about doing that?

Any help is appreciated, thanks

**Comment by davidxw** [comment]
Hi - when you say you've deployed the application using PowerShell, do you mean you've deployed using azd?  And when you say the front end, do you mean just the application code?  If so, then you can redeploy just the app (and not the Azure resources) using "azd deploy".

If you that's not the question you were asking can you clarify?
