### ISSUE TITLE
Customer can only have OpenAI deployment in the UK

### ISSUE THREAD

**Issue by Nihal-1512** [microsoft/azurechat#245]
A customer would like to deploy this solution in their environment however they can only use resources available in the UK. OpenAI resource is available in UK South but it does not show up when creating resources with Azure CLI. Is there any solution to this? Any help is appreciated, thanks.

**Comment by superpoussin22** [comment]
modify infra/main.bicep :) and add in the following line the region you want 

@allowed(['canadaeast', 'eastus', 'francecentral', 'japaneast', 'northcentralus', 'australieast', 'swedencentral'])

**Comment by Nihal-1512** [comment]
@superpoussin22, That is really helpful, thank you so much. By any chance do you know what would be required if the customer wanted to use GPT-4 instead of GPT3.5. The client has access to it, just wanted to understand how we would deploy it. Thanks again!

**Comment by mkandukuri4** [comment]
Yes, I have also deployed this solution but, how do we change to GPT4 models instead of GPT-35
