### ISSUE TITLE
Not indexing documents, error

### ISSUE THREAD

**Issue by rimvel** [microsoft/azurechat#268]
![SCR-20231201-owvf](https://github.com/microsoft/azurechat/assets/8319563/50d228f7-f112-4aae-9bfa-b54ffcef9a76)

**Comment by vtxjholter** [comment]
Also seeing this same issue.

**Comment by jussiroine** [comment]
Debugging this a bit more, the issue stems from Azure OpenAI rate limits:

"Requests to the Embeddings_Create Operation under Azure OpenAI API version 2023-09-01-preview have exceeded call rate limit of your current OpenAI S0 pricing tier. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit."

Thus, the Document Intelligence is hitting the Azure OpenAI embeddings API a bit too heavily, and I guess MSFT introduces stricter rate limits for AOAI instances in the past week, or so. Will try to see if the quota increase can be applied.

**Comment by jussiroine** [comment]
@ReginaLin24 no need to redeploy. Web App restart required, as usual to clear up any existing connectivity/sessions. The quota increase request is not needed - the quota has to be increased from within AOAI instance, and that you can do directly from the AOAI model settings.

![000139](https://github.com/microsoft/azurechat/assets/1768944/d0305f93-bfe7-4061-aab9-b14eaa2e5d62)
