### ISSUE TITLE
The account type 'FormRecognizer' is either invalid or unavailable in given region.

### ISSUE THREAD

**Issue by avistavkin** [microsoft/azurechat#274]
After one almost successful deployment of the solution, all the rest my attempts are failed with and error (detailed description is below). 

I've checked and removed all artefacts from first deployment. Checked that I can create FormRecognizer kind of accounts manually from portal.

Please suggest - where else to look?

{
  "code": "InvalidTemplateDeployment",
  "message": "The template deployment 'all-resources' is not valid according to the validation procedure. The tracking id is '1b35826c-7a58-4012-957f-82b73b8a8a99'. See inner errors for details.",
  "details": [
    {
      "code": "InvalidApiSetId",
      "message": "The account type 'FormRecognizer' is either invalid or unavailable in given region."
    }
  ]
}

**Comment by jorupp** [comment]
What region are you deploying to?  Are you deploying as the same user you're using to create the Form Recognizer from the portal?  Are you able to create all the other resources (ie. Azure OpenAI)?

**Comment by avistavkin** [comment]
> What region are you deploying to? Are you deploying as the same user you're using to create the Form Recognizer from the portal? Are you able to create all the other resources (ie. Azure OpenAI)?

Yes, the same user. And I tried different regions - EastUS, CanadaEast. Everything that normally works for me

**Comment by jorupp** [comment]
> Yes, the same user. And I tried different regions - EastUS, CanadaEast. Everything that normally works for me

Ok, doesn't sound the the issue I thought it might be then - maybe someone else has an idea.

**Comment by avistavkin** [comment]
Look! I did logout and login - and it helped! Seems something were not good with authentication or user cash...
