### ISSUE TITLE
Including DALL-E v3 means I can't deploy this version (data sovereignty) 

### ISSUE THREAD

**Issue by emdeh** [microsoft/azurechat#318]
Is there a way we can turn off the DALL-E v3 feature? I don't need that feature, but I can't deploy the solution at all because my resources must remain in Australia.

**Comment by bwitzig-zen** [comment]
You should be able to comment out the code that enables that feature. I'll let you know if I find anything.

**Comment by emdeh** [comment]
I managed to comment it out and deploy it successfully. 

Perhaps a future enhancement could be the option to turn off certain functionality before deployment. This way, if an organisation's governance landscape limits its tools because of what a particular feature does (or where it can be deployed), it can still use the other components safely.

**Comment by emdeh** [comment]
@cmvanderhaar, Check out the [test-deployment](https://github.com/emdeh/azurechat/tree/test-deployment) branch on my [forked repo](https://github.com/emdeh/azurechat). I deployed that branch and it worked. It's a little behind the upstream now, but should give you an idea of what you need to change.

**Comment by cmvanderhaar** [comment]
@emdeh thank you so much for coming back to me I really appreciate it and will check it out

**Comment by cmvanderhaar** [comment]
Hi @emdeh please if you can help with this I DO NOT want it to create images and get rid of this can you help been on this for days now

![image](https://github.com/microsoft/azurechat/assets/161803476/cb380c55-fd0a-4847-8d6d-293f7f5412d4)

**Comment by emdeh** [comment]
Hi @cmvanderhaar, I've moved on from this project, but you can see an example of how I commented out the DALL-E feature in the [main.bicep](https://github.com/emdeh/azurechat/blob/test-deployment/infra/main.bicep#L74-L109) file of my [test-deployment branch](https://github.com/emdeh/azurechat/tree/test-deployment) in the my forked [repo](https://github.com/emdeh/azurechat).

I don't recall if there were other changes, but you can review the test-deployment branch against main branch to see what other modifications I made.

Note that my fork is a bit behind the upstream now. Also, the changes I made didn't modify the frontend UI - but this wasn't my main concern. I just couldn't deploy resources to other non-Australian regions, and my changes met that objective.

**Comment by cmvanderhaar** [comment]
HI @emdeh thanks again for all the help I appreciate it
