### ISSUE TITLE
Impossible to deploy the App

### ISSUE THREAD

**Issue by jrmgodefroyRSS** [microsoft/azurechat#340]
Hello,

I have started from scratch and follow the documentation.
The creation of ressource group on my Azure subscription working well.
I have fork the project on my Github et launch the deployment scripts :
-  the bicep scripts working well
- but the build and deploy not working, I have this error :

_```
Run azure/CLI@v[1](https://github.com/XXX/azurechat/actions/runs/8047346149/job/21976447314#step:6:1)
  with:
    inlineScript: rg=$(az webapp list --query "[?name=='***'].resourceGroup" --output tsv)
  echo Setting SCM_DO_BUILD_DURING_DEPLOYMENT=false on app service ***
  az webapp config appsettings set -n *** -g $rg --settings SCM_DO_BUILD_DURING_DEPLOYMENT=false -o none
  echo Setting --startup-file=\"node server.js\" on app service ***
  az webapp config set --startup-file="node server.js" -n *** -g $rg -o none
  sleep 10
  
    azcliversion: agentazcliversion
Starting script execution via docker image mcr.microsoft.com/azure-cli:[2](https://github.com/XXX/azurechat/actions/runs/8047346149/job/21976447314#step:6:2).57.0
Setting SCM_DO_BUILD_DURING_DEPLOYMENT=false on app service ***

ERROR: argument --resource-group/-g: expected one argument

Examples from AI knowledge base:
az webapp config appsettings set --resource-group MyResourceGroup --name MyUniqueApp --settings WEBSITE_NODE_DEFAULT_VERSION=6.9.1
Set the default NodeJS version to 6.9.1 for a web app.

https://docs.microsoft.com/en-US/cli/azure/webapp/config/appsettings#az_webapp_config_appsettings_set
Read more about the command in reference docs
Error: Error: az cli script failed.
cleaning up container...
MICROSOFT_AZURE_CLI_170894[3]
Error: az cli script failed.
```_

Somebody else have already have this error ? It's look like it don't find the ressource group name to deploy

Thanks for your help

**Comment by gauravkumar796** [comment]
@jrmgodefroyRSS  I am also getting same error, can you please let me know what was the fix ?

**Comment by CyberMaciej** [comment]
what was the problem?

**Comment by pwine123** [comment]
Yes, getting the same error. What did you fix?
