### ISSUE TITLE
using gpt4

### ISSUE THREAD

**Issue by emmae157** [microsoft/azurechat#360]
hi, 

I've deployed the app in azure and when running the app, I noticed it uses gpt4 1106-preview for only text inputs and uses gpt4 vision-preview for only visual inputs. Why would it be running this way as I thought gpt4 vision-preview can take text inputs? 

Also, is the chat response quite slow for anyone? When I send "hi", it takes about 3-5 seconds to respond. When it's a short paragraph, about 14-26 seconds. Long paragraphs, up to a minute

thanks

**Comment by mkandukuri4** [comment]
Hi @emmae157,

Yes, I have also faced a lot of latency issues when the GPT version is 1106-preview, if you switch to the GA version of GPTs (GPT-35) there are low latency issues.

**Comment by emmae157** [comment]
hi @mkandukuri4,
thanks for your response, I'll try that

**Comment by sonphnt** [comment]
Yes, I have the same issue. There is an issue with GPT4-1106 preview. So we might have to wait for Microsoft to release final version.

**Comment by davidxw** [comment]
Solution has been updated to support new gpt-4o model. Note that given the speed at which new models and versions of models are released this repo might always be a little behind!
