### ISSUE TITLE
Use GPT4o new model

### ISSUE THREAD

**Issue by surendransuri** [microsoft/azurechat#384]
How to use GPT4o new model into this solution

**Comment by kkabza** [comment]
its not in azure yet.

**Comment by vlad-tsoy** [comment]
Yes, it is. It's been in preview since the OpenAI's announcement and was announced GA at the MS Build.

**Comment by Sandeep-FED** [comment]
@surendransuri, deploy 4o model in azure openai and add its key, endpoints in azure environment variables. But this will not unlock the full potential of 4o cause its need dev changes.

**Comment by davidxw** [comment]
We've just pushed an update that implements gpt-4o and consolidates the openAI and vision models.
