### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

### ISSUE THREAD

**Issue by na20aak-herts** [microsoft/azurechat#386]
I have deployed the solution in a customers environment but I am getting this error. I am unable to see the chat pages or persona pages, I get this error instead. Can anyone please advise on how to fix. It is really urgent, thanks so much.

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

![image](https://github.com/microsoft/azurechat/assets/154440888/e18f0c29-8693-4957-a7a0-f8109a0186e2)

**Comment by woodyjon** [comment]
I have the same error. Did you fix it? How? (I see that you closed it)

**Comment by na20aak-herts** [comment]
Interestingly enough I didn't do anything, my access wasn't eligible to view the pages. However, the customer was able to view and use the application without any issues. It was due to the way the access was set up in their tenant for users who aren't employees.

**Comment by murdockcrc** [comment]
This happens in the logged in user's session does not have an email address.

In my case, my user's `session.user.email` was `undefined`. The logged in user must have an email address.
