### ISSUE TITLE
Extensions with delegated permissions scope / Graph APIs

### ISSUE THREAD

**Issue by DakotaWray2** [microsoft/azurechat#411]
I'm interested if anyone has extended this accelerator to implement extensions that use delegated permissions to access data from Microsoft Graph? Thanks!

**Comment by DakotaWray2** [comment]
Hi folks I just wanted to follow-up that I have achieved this.

- First step was to modify auth-api.ts to handle permission scopes for azuread and pass the accessToken in session.
- Second step was to modify chat-api-default-extensions.ts to add new default extensions that utilize @microsoft/microsoft-graph-client. 
- Lastly modify the default persona to know that it can call the default functions that use graph.

I need to figure out the token refresh logic but it is working well!

**Comment by toellbe** [comment]
@DakotaWray2 Can you share some snippets?

**Comment by DakotaWray2** [comment]
@toellbe For this I cannot but if you look into next-auth / EntraID integration there are quite a few explanations. From what I recall pass the access token to the session but not the refresh token. And look in to how to gracefully handle the token refresh. I don't think there is an OTB handler for this in next-auth.
