### ISSUE TITLE
Changed Layout

### ISSUE THREAD

**Issue by agg-anwarulislam** [microsoft/azurechat#450]
Has anyone managed to change the this layout, if so how please. 

![Image](https://github.com/user-attachments/assets/78a3799c-6780-4027-bcff-ead89ad4a2cc)

**Comment by Lucas-almma** [comment]
It is one of the biggest problems with Azure Chat. The layout and UX/UI show a lot of room for improvement.

We have this.

![Image](https://github.com/user-attachments/assets/dcb62945-ce0f-4124-8285-29fee4c42bf7)

**Comment by agg-anwarulislam** [comment]
@Lucas-almma thank you, i am a newbie, but how do i change the Ui

**Comment by DakotaWray2** [comment]
Azurechat's UI is built with ShadCN/UI which itself leverages Tailwind css and Radix UI. I would start there to understand how to extend the baked in component styling.
